 - name: Copy Prometheus config
   ansible.builtin.template:
     src: "{{item}}.yml"
     dest: /opt/prometheus/{{item}}.yml
   loop:
     - prometheus
     - alerts

 - name: Restart Prometheus
   ansible.builtin.systemd:
     name: prometheus
     state: restarted

# - name: Check if prometheus is running or not
#   ansible.builtin.shell: sleep 10 ; netstat -lntp | grep 9090

 - name: wait for prometheus is started or not
   ansible.builtin.wait_for:
     port: 9090
     delay: 10
     timeout: 15
